# Generated by Django 5.2.9 on 2026-01-04 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0003_notification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenancerequest",
            name="client",
            field=models.ForeignKey(
                blank=True,
                help_text="The client (user) this request is for",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="client_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="maintenancerequest",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
